# Generated by Django 2.1.2 on 2019-01-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0003_auto_20190116_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('shifts', models.ManyToManyField(to='scheduler_app.Shift')),
            ],
        ),
    ]
